server:
  port: 8081

spring:
  application:
    name: USERSERVICE # Application name registered with Eureka or config server

  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Automatically update the schema based on entity changes
    show-sql: true # Logs SQL queries to the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8.x dialect

  config:
    import: configserver:http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-52889595.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oal7errm5pKGVdXd5d7
            client-secret: hH8Pl33uNizEINLWnsD5y2pvim9uGr-XnJRqMbj9b6UH0-Q66VhUKIj6mzlr0ZYZ

        provider:
          okta:
            issuer-uri: https://dev-52889595.okta.com/oauth2/default



 # profiles:
  #  active: dev

  #  eureka:
  #    instances:
  #      prefer-ip-address: true
  #    client:
  #      fetch-registry: true
  #      register-with-eureka: true
  #      service-url:
  #        defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instance:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instance:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s


okta:
  oauth2:
    issuer: https://dev-52889595.okta.com/oauth2/default
    audience: api://default
    client-id: 0oal7errm5pKGVdXd5d7
    client-secret: hH8Pl33uNizEINLWnsD5y2pvim9uGr-XnJRqMbj9b6UH0-Q66VhUKIj6mzlr0ZYZ
    scopes: openid, profile, email, offline_access
